[mongodb]
mongodb-dev.ramyaboutique.shop

[catalogue]
catalogue-dev.ramyaboutique.shop

[mysql]
mysql-dev.ramyaboutique.shop

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.ramyaboutique.shop

[redis]
redis-dev.ramyaboutique.shop

[user]
user-dev.ramyaboutique.shop

[cart]
cart-dev.ramyaboutique.shop

[shipping]
shipping-dev.ramyaboutique.shop

[rabbitmq]
rabbitmq-dev.ramyaboutique.shop

[payment]
payment-dev.ramyaboutique.shop

[frontend]
frontend-dev.ramyaboutique.shop
